cluster.name: docker-cluster
network.host: 0.0.0.0

discovery.type: single-node

## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
xpack.security.enabled: true
xpack.license.self_generated.type: trial